server:
  port: 8000

spring:
  config:
    import:
      - optional:consul:/**

  application:
    name: gateway

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    consul:
      enabled: true
      discovery:
        query-passing: true

    gateway:
      routes:
        - id: multiplication
          uri: http://localhost:8080/
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/users/**

        - id: gamification
          uri: http://localhost:8081/
          predicates:
            - Path=/leaders

      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET, POST
